#ifndef LAYOUTVIEWPLUGIN_GLOBAL_H
#define LAYOUTVIEWPLUGIN_GLOBAL_H

#include <QLoggingCategory>
#include <QtCore/qglobal.h>

Q_DECLARE_LOGGING_CATEGORY (CPR_PLUGIN_LAYOUT)

#endif // LAYOUTVIEWPLUGIN_GLOBAL_H
