#ifndef PROPERTIESVIEW_GLOBAL_H
#define PROPERTIESVIEW_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PROPERTIESVIEW_LIBRARY)
#  define PROPERTIESVIEWSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PROPERTIESVIEWSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PROPERTIESVIEW_GLOBAL_H
