#ifndef NCLTEXTUALVIEWPLUGIN_GLOBAL_H
#define NCLTEXTUALVIEWPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TEXTUALVIEWPLUGIN_LIBRARY)
#  define TEXTUALVIEWPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define TEXTUALVIEWPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TEXTUALVIEWPLUGIN_GLOBAL_H
