#ifndef CPMODELPROFILE_GLOBAL_H
#define CPMODELPROFILE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CPMODELPROFILE_LIBRARY)
#  define CPMODELPROFILE_LIBRARY Q_DECL_EXPORT
#else
#  define CPMODELPROFILE_LIBRARY Q_DECL_IMPORT
#endif


#endif // CPMODELPROFILE_GLOBAL_H
