[[sec:tutorial]]
Tutorial
--------
Este tutorial é o ponto de partida para os interessados em desenvolver
aplicações para TV Digital usando o
http://composer.telemidia.puc-rio.br[{nclcomposer}].

Baseado nos exemplos apresentados no Capítulo 3 do livro 
http://www.telemidia.puc-rio.br[Programando em NCL 3.0], este tutorial traz uma
introdução passo a passo de como utilizar o {nclcomposer} para o 
desenvolvimento de aplicações interativas usando a NCL 3.0 para TV digital.

Alguns conhecimentos são necessários para prosseguir:

	* Básico em Informática.
	* http://www.ncl.org.br[Linguagem NCL 3.0 (Nested Context Language)] (pode ser
  	estudada junto com o tutorial).

Exemplos:

	* Exemplo 0: <<sample:00, Olá Garrincha!>>
	* Exemplo 1: <<sample:01, Sincronismo sem interatividade>>
	* Exemplo 2: Sincronismo com interatividade
	* Exempl0 3: Contextos
	* Exemplo 4: Reúso de Objetos de Mídia
	* Exemplo 5: Canal de Interatividade
	* Exemplo 6: Múltiplos dispositivos
	* Exemplo 7: Adaptação de Conteúdo
	* Exemplo 8: Nó Settings
	* Exemplo 9: Efeitos de Transição e Animação
	* Exemplo 10: Navegação por teclas
	* Exemplo 11: Objetos NCLua

// [NOTE]
// ******
Neste tutorial, não existe a preocupação nem de definir a linguagem NCL
completamente e nem de apresentar todas as funcionalidades do {nclcomposer}. Os
exemplos são desenvolvidos seguindo o que os autores acreditam que seja a
forma mais prática de utilização da ferramenta.

Para uma referência completa sobre a linguagem NCL, recomendamos:

  * O livro Programando em NCL 3.0 <<Soares2012>> (português); ou
  * o http://handbook.ncl.org.br[NCL Handbook] (inglês).

Para uma referência completa sobre o {nclcomposer}, é possível consultar o:

  * http://composer.telemidia.puc-rio.br[{nclcomposer} User Manual] (inglês).

Sempre que necessário, no entanto, no decorrer deste tutorial, é possível
encontrar ponteiros para partes específicas do http://handbook.ncl.org.br[NCL
Handbook] ou para o http://composer.telemidia.puc-rio.br[{nclcomposer} User
Manual] onde o leitor pode encontrar mais informações.
// ******

Assim como no Capítulo 3 do Livro Programando em NCL, para introduzir a
programação em NCL usando o {nclcomposer}, iremos utilizar um único exemplo,
que será construído passo a passo: _O Primeiro João_.

_O Primeiro João_ é baseado em um vídeo, uma animação de mesmo nome
produzida por André Castelão, que por sua vez foi baseado nas crônicas de 
Mané Garrincha, escritas por Gerson Soares. 

NOTE: Uma descrição completa da animação _O Primeiro João_ pode ser encontrada
em: <<Soares2012>>.

// Include the example 01
include::tutorial_ex01.asciidoc[]

// Include the example 02
include::tutorial_ex02.asciidoc[]


Exemplo 3: Sincronismo com Interatividade
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
TODO

Exemplo 4: Contextos
~~~~~~~~~~~~~~~~~~~~
TODO

Exemplo 5: Reúso de Objetos de Mídia
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
TODO

Exemplo 6: Canal de Interatividade
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
TODO

Exemplo 7: Múltiplos Dispositivos de Exibição
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
TODO

Exemplo 8: Adaptação de Conteúdo
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
TODO

Exemplo 9: Nó Settings
~~~~~~~~~~~~~~~~~~~~~~
TODO

Exemplo 10: Efeitos de Transição e Animação
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
TODO

Exemplo 11: Navegação por Teclas
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
TODO

Exemplo 12: Objetos NCLua
~~~~~~~~~~~~~~~~~~~~~~~~~
TODO
