#ifndef NCLLANGUAGEPROFILE_GLOBAL_H
#define NCLLANGUAGEPROFILE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(NCLLANGUAGEPROFILE_LIBRARY)
#  define NCLLANGUAGEPROFILESHARED_EXPORT Q_DECL_EXPORT
#else
#  define NCLLANGUAGEPROFILESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // NCLLANGUAGEPROFILE_GLOBAL_H
